re-enable idle scripts
HASwitchPlate/openHASP pull request #625
Opened 2024-01-27 14:13 UTC by hb020

See https://github.com/HASwitchPlate/openHASP/issues/618

The idle scripts were inoperative since a recent commit.

Not sure if what I claim is true, but this is my interpretation: Since:
* ```dispatch_idle_state()``` seems to be called also when a state situation is requested (dispatch_current_state())
* ```dispatch_idle()``` seems to be called only upon startup
* ```hasp_set_sleep_state()``` seems to be deprecated

and we want the scripts to be called only when the state changes, I decided to put the scripts directly in the function that detects the changes: ```hasp_update_sleep_state()```

2024-01-27 14:49 UTC, fvanroie requested changes
TAG_MAIN should be TAG_HASP

2024-01-27 14:52 UTC, hb020 commented
Done

2024-01-28 13:01 UTC, fvanroie approved these changes

2024-01-28 13:02 UTC, merged

2024-01-28 13:03 UTC, fvanroie commented
Thanks!